version: "3"
services:
  app:
    build: .
    working_dir: /home/node/app
    container_name: "rickandmortyapp"
    ports:
      - "0.0.0.0:5100:3000"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "5100"